export const EVENT_TYPES = {
  REQUEST_KYC_CONNECTION: "REQUEST_KYC_CONNECTION",
  RESPONSE_KYC_CONNECTION: "RESPONSE_KYC_CONNECTION",
  CONFIRM_POPUP_RESPONSE_KYC_CONNECTION:
    "CONFIRM_POPUP_RESPONSE_KYC_CONNECTION",
  KYC_APPROVAL_REQUEST: "KYC_APPROVAL_REQUEST",
  KYC_APPROVAL_RESPONSE: "KYC_APPROVAL_RESPONSE",
  CONFIRM_POPUP_RESPONSE_KYC_APPROVAL: "CONFIRM_POPUP_RESPONSE_KYC_APPROVAL",
  ACCESS_LOGIN_TOKEN: "ACCESS_LOGIN_TOKEN",
  LOGIN_TOKEN: "LOGIN_TOKEN",
  DISPATCH: "DISPATCH",
};
